from typing import Protocol, runtime_checkable

from ai_accounts_core.domain.backend import Backend, BackendCredential
from ai_accounts_core.domain.chat import ChatMessage, ChatSession
from ai_accounts_core.domain.onboarding import OnboardingState
from ai_accounts_core.domain.session import LiveSession


@runtime_checkable
class BackendRepository(Protocol):
    async def create(self, backend: Backend) -> None: ...
    async def get(self, backend_id: str) -> Backend | None: ...
    async def list(self) -> list[Backend]: ...
    async def update(self, backend: Backend) -> None: ...
    async def delete(self, backend_id: str) -> None: ...

    async def put_credential(self, credential: BackendCredential) -> None: ...
    async def get_credential(self, backend_id: str) -> BackendCredential | None: ...
    async def delete_credential(self, backend_id: str) -> None: ...


@runtime_checkable
class SessionRepository(Protocol):
    async def upsert(self, session: LiveSession) -> None: ...
    async def get(self, session_id: str) -> LiveSession | None: ...
    async def list_active(self) -> list[LiveSession]: ...
    async def end(self, session_id: str) -> None: ...


@runtime_checkable
class HistoryRepository(Protocol):
    async def create_session(self, session: ChatSession) -> None: ...
    async def append_message(self, message: ChatMessage) -> None: ...
    async def list_messages(self, session_id: str) -> list[ChatMessage]: ...
    async def list_sessions(self, backend_id: str | None = None) -> list[ChatSession]: ...


@runtime_checkable
class OnboardingRepository(Protocol):
    async def get(self, onboarding_id: str) -> OnboardingState | None: ...
    async def put(self, state: OnboardingState) -> None: ...


@runtime_checkable
class StorageProtocol(Protocol):
    async def backends(self) -> BackendRepository: ...
    async def sessions(self) -> SessionRepository: ...
    async def history(self) -> HistoryRepository: ...
    async def onboarding(self) -> OnboardingRepository: ...
    async def migrate(self) -> None: ...
    async def close(self) -> None: ...
