/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/backends": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** ListBackends */
        get: operations["ApiV1BackendsListBackends"];
        put?: never;
        /** CreateBackend */
        post: operations["ApiV1BackendsCreateBackend"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/backends/{backend_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** GetBackend */
        get: operations["ApiV1BackendsBackendIdGetBackend"];
        put?: never;
        post?: never;
        /** DeleteBackend */
        delete: operations["ApiV1BackendsBackendIdDeleteBackend"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/backends/{backend_id}/detect": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Detect */
        post: operations["ApiV1BackendsBackendIdDetectDetect"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/backends/{backend_id}/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["ApiV1BackendsBackendIdLoginLogin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/backends/{backend_id}/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Validate */
        post: operations["ApiV1BackendsBackendIdValidateValidate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["HealthHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** BackendDTO */
        BackendDTO: {
            config: {
                [key: string]: unknown;
            };
            display_name: string;
            id: string;
            kind: string;
            last_error?: string | null;
            status: string;
        };
        /** BackendListDTO */
        BackendListDTO: {
            items: components["schemas"]["BackendDTO"][];
        };
        /** CreateBackendRequest */
        CreateBackendRequest: {
            config?: {
                [key: string]: unknown;
            };
            display_name: string;
            kind: string;
        };
        /** DetectResultDTO */
        DetectResultDTO: {
            installed: boolean;
            notes?: string | null;
            path?: string | null;
            version?: string | null;
        };
        /** LoginRequest */
        LoginRequest: {
            flow_kind: string;
            inputs?: {
                [key: string]: string;
            };
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    ApiV1BackendsListBackends: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Request fulfilled, document follows */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BackendListDTO"];
                };
            };
        };
    };
    ApiV1BackendsCreateBackend: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateBackendRequest"];
            };
        };
        responses: {
            /** @description Document created, URL follows */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BackendDTO"];
                };
            };
            /** @description Bad request syntax or unsupported method */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        detail: string;
                        extra?: null | {
                            [key: string]: unknown;
                        } | unknown[];
                        status_code: number;
                    };
                };
            };
        };
    };
    ApiV1BackendsBackendIdGetBackend: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                backend_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Request fulfilled, document follows */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BackendDTO"];
                };
            };
            /** @description Bad request syntax or unsupported method */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        detail: string;
                        extra?: null | {
                            [key: string]: unknown;
                        } | unknown[];
                        status_code: number;
                    };
                };
            };
        };
    };
    ApiV1BackendsBackendIdDeleteBackend: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                backend_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Request fulfilled, nothing follows */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Bad request syntax or unsupported method */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        detail: string;
                        extra?: null | {
                            [key: string]: unknown;
                        } | unknown[];
                        status_code: number;
                    };
                };
            };
        };
    };
    ApiV1BackendsBackendIdDetectDetect: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                backend_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Document created, URL follows */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DetectResultDTO"];
                };
            };
            /** @description Bad request syntax or unsupported method */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        detail: string;
                        extra?: null | {
                            [key: string]: unknown;
                        } | unknown[];
                        status_code: number;
                    };
                };
            };
        };
    };
    ApiV1BackendsBackendIdLoginLogin: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                backend_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Document created, URL follows */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BackendDTO"];
                };
            };
            /** @description Bad request syntax or unsupported method */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        detail: string;
                        extra?: null | {
                            [key: string]: unknown;
                        } | unknown[];
                        status_code: number;
                    };
                };
            };
        };
    };
    ApiV1BackendsBackendIdValidateValidate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                backend_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Document created, URL follows */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BackendDTO"];
                };
            };
            /** @description Bad request syntax or unsupported method */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        detail: string;
                        extra?: null | {
                            [key: string]: unknown;
                        } | unknown[];
                        status_code: number;
                    };
                };
            };
        };
    };
    HealthHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Request fulfilled, document follows */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
